services:
    morket_hmvc.agent:
        class: Morket\Bundle\HMVCBundle\HMVC\Agent
        scope: request
        arguments: [@request, @router, @http_kernel]
    morket_hmvc.response_factory:
        class: Morket\Bundle\HMVCBundle\HttpFoundation\ResponseFactory
    morket_hmvc.raw_response_listener:
        class: Morket\Bundle\HMVCBundle\EventListener\RawResponseListener
        arguments: [@morket_hmvc.response_factory]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 128 }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 128 }