language: php

php:
  - 5.4
  - 5.3
env:
  - SYMFONY_VERSION='2.1.*'

before_script:
  - composer self-update
  - composer require --no-update symfony/symfony=$SYMFONY_VERSION
  - composer install --prefer-source --dev

script: ./bin/phpspec run -fpretty
